kind: Deployment
apiVersion: apps/v1
metadata:
  name: jmeter-kafka
  namespace: rt-inventory-dev
  labels:
    app: jmeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmeter
      deployment: jmeter-kafka
  template:
    metadata:
      labels:
        app: jmeter
        deployment: jmeter-kafka
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: jmeter-kafka
          image: >-
            quay.io/ibmcase/jmeter-kafka
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: BATCH_SIZE
              value: '700'
            - name: BOOTSTRAP_SERVERS
              value: 'dev-kafka-bootstrap.rt-inventory-dev.svc:9092'
            - name: HEAP
              value: '-Xms512m -Xmx4096m'
            - name: JMETER_THREADS
              value: '100'
            - name: KAFKA_TOPIC
              value: perf-p1r3
            - name: LOOP_COUNT
              value: '50000'
            - name: PROMETHEUS_HOST
              value: 0.0.0.0
            - name: PROMETHEUS_PORT
              value: '8080'
            - name: RAMUP_PERIOD
              value: '60'
            - name: SAMPLER_LABEL
              value: test-1k
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600