apiVersion: batch/v1
kind: Job
metadata:
  name: cp-scram-usr-secret
  namespace: rt-inventory-dev
spec:
  template:
    metadata:
      name: cp-tls-usr-secret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret eda-scram-user -n rt-inventory-dev | grep found)\" ]; \
          then kubectl get secret eda-scram-user -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"rt-inventory-dev\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences,  .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n rt-inventory-dev -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
