apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: item-inventory
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  partitions: 1
  replicas: 3

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: items
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  partitions: 1
  replicas: 3

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: store-inventory
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  partitions: 1
  replicas: 3