apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_TARGET_MESSAGING: kafka,IBMMQ
  KAFKA_BOOTSTRAP_SERVERS: es-demo-kafka-bootstrap-cp4i-eventstreams.apps.ahsoka.coc-ibm.com:443
  #es-demo-kafka-bootstrap.cp4i-eventstreams.svc:9093
  
  KAFKA_TOPIC_NAME: eda-rt-items
  # MP_MESSAGING_OUTGOING_ITEMS_APICURIO_REGISTRY_AUTO_REGISTER: "false"
  # MP_MESSAGING_OUTGOING_ITEMS_VALUE_SERIALIZER: io.quarkus.kafka.client.serialization.JsonbSerializer
  ES_APICURIO_URL: https://es-demo-ibm-es-ac-reg-external-cp4i-eventstreams.apps.ahsoka.coc-ibm.com/apis/registry/v2
  MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE: "USER_INFO"
  MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: scram-user-schema:cDGz4C2WX7Uf
  # mp.messaging.connector.smallrye-kafka.apicurio.registry.basic.auth.credentials.source=USER_INFO
  # mp.messaging.connector.smallrye-kafka.apicurio.registry.schema.registry.basic.auth.user.info=scram-user-schema
  MQ_HOST: store-mq-ibm-mq.rt-inventory-dev.svc
  # external: mq1-cp4i-ibm-mq-qm-cp4i-mq1.apps.biggs.coc-ibm.com
  MQ_PORT: "1414"
  MQ_QMGR: QM1 
  MQ_QUEUE_NAME: ITEMS
  MQ_CHANNEL: DEV.APP.SVRCONN