apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_TARGET_MESSAGING: kafka,IBMMQ
  KAFKA_BOOTSTRAP_SERVERS: es-demo-kafka-bootstrap.cp4i-eventstreams.svc:9093
  KAFKA_TOPIC_NAME: eda-rt-items
  KAFKA_SECURITY_PROTOCOL: SSL
  ES_APICURIO_URL: https://es-demo-ibm-es-ac-reg-external-cp4i-eventstreams.apps.ahsoka.coc-ibm.com/apis/registry/v2
  MQ_HOST: store-mq-ibm-mq.rt-inventory-dev.svc
  # external: mq1-cp4i-ibm-mq-qm-cp4i-mq1.apps.biggs.coc-ibm.com
  MQ_PORT: "1414"
  MQ_QMGR: QM1 
  MQ_QUEUE_NAME: ITEMS
  MQ_CHANNEL: DEV.APP.SVRCONN