# Project information
site_name: Kafka Mirror Maker 2
repo_url: https://github.com/[YOUR_GITHUB_ID]/[YOUR-REPOSITORY-NAME]


# Navigation
nav:
  - Mirror Maker 2: index.md

# Theme
theme: 
  name: material
  palette:
    scheme: default
    primary: 'blue'
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.instant
      - navigation.indexes
      - navigation.tracking
      - navigation.tabs.sticky
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - pymdownx.highlight
  - meta
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
