apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: prod
  namespace: rt-inventory-staging
spec:
  version: 11.0.1
  license:
    accept: true
    use: CloudPakForIntegrationProduction
  requestIbmServices:
    iam: true
    monitoring: true
  adminApi: {}
  adminUI: {}
  apicurioRegistry:
    livenessProbe:
      initialDelaySeconds: 120
  collector: {}
  restProducer: {}
  strimziOverrides:
    entityOperator: 
      topicOperator:
        resources:
          limits:
            cpu: 500m
            memory: 3Gi
          requests:
            cpu: 90m
            memory: 2Gi
        template:
          pod:
            tmpDirSizeLimit: 100Mi
      userOperator:
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 203m
            memory: 650Mi
        template:
          pod:
            tmpDirSizeLimit: 5Mi
    kafka:
      replicas: 3
      metrics: {}
      rack:
        topologyKey: topology.kubernetes.io/zone
      resources:
        requests:
          cpu: 4000m
          memory: 8096Mi
        limits:
          cpu: 4000m
          memory: 8096Mi
      authorization:
        authorizerClass: com.ibm.eventstreams.runas.authorizer.RunAsAuthorizer
        supportsAdminApi: true
        type: custom
      config:
        inter.broker.protocol.version: '3.0'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        num.network.threads: 9
        log.cleaner.threads: 6
        num.io.threads: 24
        num.replica.fetchers: 3
        min.insync.replicas: 2
        log.message.format.version: '3.0'
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
      listeners:
        - name: plain
          type: internal
          port: 9092
          tls: false
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      storage:
        type: persistent-claim
        size: 10Gi
        class: ocs-storagecluster-ceph-rbd
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: metrics-config
      template:
          pod:
            tmpDirSizeLimit: 5Mi
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: metrics-config
      storage:
        type: persistent-claim
        size: 4Gi
        class: ocs-storagecluster-ceph-rbd
      template:
          pod:
            tmpDirSizeLimit: 5Mi
    cruiseControl: {}
