apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: rti-kconnect-cluster
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  version: 3.2.0
  replicas: 1
  bootstrapServers: dev-kafka-bootstrap.rt-inventory-dev.svc:9092
  image: quay.io/ibmcase/eda-kconnect-cluster-image:latest
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  template:
    pod:
      tmpDirSizeLimit: 100Mi
      imagePullSecrets: []
      metadata:
        annotations:
          productChargedContainers: rti-kconnect-cluster-connect
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 11.0.3
          productMetric: VIRTUAL_PROCESSOR_CORE
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          cloudpakVersion: 2022.2.1
          productCloudpakRatio: "2:1"
  config:
    group.id: rti-connect-cluster
    offset.storage.topic: rti-connect-cluster-offsets
    config.storage.topic: rti-connect-cluster-configs
    status.storage.topic: rti-connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    offset.storage.cleanup.policy: compact
    status.storage.replication.factor: 3
    
  externalConfiguration:
    env:
      - name: IBM_COS_API_KEY
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.api.key
      - name: IBM_COS_BUCKET_LOCATION
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.bucket.location
      - name: IBM_COS_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.bucket.name
      - name: IBM_COS_RESILIENCY
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.bucket.resiliency
      - name: IBM_COS_CRM
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.service.crn
#  tls:
#    trustedCertificates:
#      - secretName: quickstart-cluster-ca-cert
#        certificate: ca.crt
#  authentication:
#    type: scram-sha-512
#    username: my-connect-user
#    passwordSecret:
#      secretName: my-connect-user
#      password: my-connect-password-key
