apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp4i-job-sa
  namespace: cp4i
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: cp4i-job-sa
    namespace: cp4i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin