apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: store-simulator
    app.kubernetes.io/version: 0.0.10
  name: store-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: store-simulator
      app.kubernetes.io/version: 0.0.10
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store-simulator
        app.kubernetes.io/version: 0.0.10
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: /deployments/certs/server/ca.p12
            - name: KAFKA_SSL_TRUSTSTORE_TYPE
              value: PKCS12
            - name: KAFKA_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_CERT_PWD
              valueFrom:
                secretKeyRef:
                  key: ca.password
                  name: dev-cluster-ca-cert
          envFrom:
            - configMapRef:
                name: store-simulator-cm
          image: quay.io/ibmcase/eda-store-simulator:0.0.15
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: store-simulator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /deployments/certs/server
            name: kafka-cert
            readOnly: false
            subPath: ""
      serviceAccount: store-simulator
      volumes:
      - name: kafka-cert
        secret:
          optional: true
          secretName: dev-cluster-ca-cert
