#!/bin/bash
# This tool can only be executed in the secrets folder created by KAM CLI.
# Once done the secret sealed are in this folder and only the defineSecrets
# should be run
# This tool is to reuse only for future project

NS=sealed-secrets
CTL_NAME=sealed-secrets-controller

function generateSecret(){
    cat $1 | kubeseal --controller-namespace  $NS \
    --controller-name $CTL_NAME --format yaml > $2
}

#cd ../secrets

generateSecret docker-config.yaml docker-config-sealed.yaml 
generateSecret git-host-access-token.yaml git-host-access-token-sealed.yaml 
generateSecret git-host-basic-auth-token.yaml git-host-basic-auth-token-sealed.yaml
generateSecret gitops-webhook-secret.yaml gitops-webhook-secret-sealed.yaml
generateSecret webhook-secret-rt-inventory-dev-refarch-eda-store-simulator.yaml webhook-secret-rt-inventory-dev-refarch-eda-store-simulator-sealed.yaml
generateSecret webhook-secret-rt-inventory-dev-store-inventory.yaml webhook-secret-rt-inventory-dev-store-inventory-sealed.yaml
generateSecret webhook-secret-rt-inventory-dev-item-inventory.yaml webhook-secret-rt-inventory-dev-item-inventory-sealed.yaml

