#!/bin/bash

oc apply -f docker-config-sealed.yaml 
oc apply -f git-host-access-token-sealed.yaml
oc apply -f git-host-basic-auth-token-sealed.yaml
oc apply -f gitops-webhook-secret-sealed.yaml    
oc apply -f webhook-secret-rt-inventory-dev-refarch-eda-store-simulator-sealed.yaml
oc apply -f webhook-secret-rt-inventory-dev-store-inventory-sealed.yaml
oc apply -f webhook-secret-rt-inventory-dev-item-inventory-sealed.yaml